server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/baoliao?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Bingbet
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

#扫描二维码后跳转的域名
domain_name: http://cailiao.bingbet.net

#上传图片存储位置
product_img_path: /root/servers/file_server/tomcat8534/webapps/ROOT/userImg/

#生成的二维码位置
qr_code_img_path: /root/servers/file_server/tomcat8534/webapps/ROOT/QRCodeImg/

#证书地址
certificate_path: /root/servers/file_server/jdk8/zhengshu/