server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/baoliao?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    #    password: root
    password: 123456
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

domain_name: http://28nmdc.natappfree.cc

#上传图片存储位置
product_img_path: /root/servers/file_server/tomcat8534/webapps/ROOT/userImg/
#生成的二维码位置
qr_code_img_path: /root/servers/file_server/tomcat8534/webapps/ROOT/QRCodeImg/
logging:
  level:
    com.baoliao.weixin.dao: debug