

server:
  port: 80
mybatis:
  mapper-locations: classpath:com/baoliao/weixin/mapper/*Mapper.xml
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/baoliao?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    #    password: root
    password: 123456
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp